spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  resources:
    static-locations: classpath:/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  datasource:
    url: jdbc:mysql://59.110.229.77:3306/examination-analysis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: MARIA123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  tomcat:
    uri-encoding: UTF-8
  port: 80