spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  resources:
    static-locations: classpath:/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /

server:
  tomcat:
    uri-encoding: UTF-8